os:
  - linux
  - osx
language: ruby # need a language distro with postgres installed.
sudo: required
dist: trusty
osx_image: xcode8
addons:
  postgresql: "9.5"
services:
  - postgresql
before_script:
  - sudo psql -U postgres -c 'CREATE DATABASE test;'
script:
  - eval "$(curl -sL swift.vapor.sh/ci)"
  - eval "$(curl -sL swift.vapor.sh/codecov)"
